version: '3.1'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: nginxproxy/acme-companion
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh

  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/mysql:/var/lib/mysql

  danfey-nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./web/nginx/danfey.conf:/etc/nginx/conf.d/danfey.conf:ro
      - ./web/danfey:/var/www/html
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=danfey.com,fey.dev
      - LETSENCRYPT_HOST=danfey.com,fey.dev

  danfey-wordpress:
    image: wordpress:php7.2-fpm-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./web/danfey:/var/www/html

  entogronomy-nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./web/nginx/entogronomy.conf:/etc/nginx/conf.d/entogronomy.conf:ro
      - ./web/entogronomy:/var/www/html
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=entogronomy.com
      - LETSENCRYPT_HOST=entogronomy.com

  entogronomy-php:
    image: php:7.2-fpm-alpine
    restart: always
    volumes:
      - ./web/entogronomy:/var/www/html

  satisfactory-start:
    build: ./web/satisfactory-start
    restart: always
    expose:
      - "80"
    env_file:
      - ./web/satisfactory-start/.env

volumes:
  acme:
  certs:
  vhost:
  html:
