version: '3.1'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - ./web/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./web/nginx/certs:/etc/nginx/certs:rw
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/mysql:/var/lib/mysql

  danfey-nginx:
    image: nginx:stable-alpine
    volumes:
      - ./web/nginx/danfey.conf:/etc/nginx/conf.d/danfey.conf:ro
      - ./web/danfey:/var/www/html
    environment:
      - VIRTUAL_HOST=danfey.com
      - LETSENCRYPT_HOST=danfey.com
      - LETSENCRYPT_EMAIL=${EMAIL}

  danfey-wordpress:
    image: wordpress:php7.2-fpm-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./web/danfey:/var/www/html

  entogronomy-nginx:
    image: nginx:stable-alpine
    volumes:
       - ./web/nginx/entogronomy.conf:/etc/nginx/conf.d/entogronomy.conf:ro
       - ./web/entogronomy:/var/www/html
    environment:
      - VIRTUAL_HOST=entogronomy.com
      - LETSENCRYPT_HOST=entogronomy.com
      - LETSENCRYPT_EMAIL=${EMAIL}

  entogronomy-php:
    image: php:7.2-fpm-alpine
    restart: always
    volumes:
      - ./web/entogronomy:/var/www/html

  wedding-nginx:
    image: nginx:stable-alpine
    volumes:
      - ./web/nginx/wedding.conf:/etc/nginx/conf.d/wedding.conf:ro
      - ./web/wedding:/var/www/html
    environment:
      - VIRTUAL_HOST=hannaanddan.wedding
      - LETSENCRYPT_HOST=hannaanddan.wedding
      - LETSENCRYPT_EMAIL=${EMAIL}

volumes:
  nginx-vhost:
  nginx-html: